language: go
os:
 - linux
 - windows

go:
 - "1.10"
 - "1.11"
 - "1.12"
 - 1.x

install:
  - go get github.com/apexskier/httpauth
  - go get github.com/go-ini/ini
  - go get github.com/gorilla/mux
  - go get github.com/hpcloud/tail
  - go get github.com/gorilla/websocket
  - go get github.com/majormjr/rcon

script:
 - go test -v ./...
