on: [push, pull_request]
jobs:
  test-npm:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: make app/bundle
  test-go:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: ['1.14', '1.15', '1']
    runs-on: ${{ matrix.os }}
    name: test-go ${{ matrix.go }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: cd src; go test ./...
