on: [push, pull_request]
jobs:
  test-npm:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: make app/bundle
  test-go:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: ['1.14', '1.15', '1']
    runs-on: ${{ matrix.os }}
    name: test-go ${{ matrix.go }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: cd src; go test ./...
  docker-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/github-actions'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-go@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make build; cp build/factorio-server-manager-linux.zip docker/factorio-server-manager-linux.zip
      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: Dockerfile-local
          push: true
          tags: ofsm/ofsm:github-actions
